name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Stylemark
      run: npm install && npm run build
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build Flask
      run: cd flask && pip install -r requirements.txt && python freeze.py
    - name: Deploy to GH pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
          build_dir: dist
          jekyll: false
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
